-- MySQL Script generated by MySQL Workbench
-- 05/14/19 22:06:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jmbm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jmbm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jmbm` ;
USE `jmbm` ;

-- -----------------------------------------------------
-- Table `jmbm`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmbm`.`profesor` (
  `idprofesor` INT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `numerocc` VARCHAR(45) NULL,
  PRIMARY KEY (`idprofesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jmbm`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmbm`.`grado` (
  `idgrado` INT NULL,
  `grado` INT(30) NULL,
  PRIMARY KEY (`idgrado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jmbm`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmbm`.`grupo` (
  `idgrupo` INT NULL,
  `grado_idgrado` INT NOT NULL,
  PRIMARY KEY (`idgrupo`, `grado_idgrado`),
  INDEX `fk_grupo_grado1_idx` (`grado_idgrado` ASC),
  CONSTRAINT `fk_grupo_grado1`
    FOREIGN KEY (`grado_idgrado`)
    REFERENCES `jmbm`.`grado` (`idgrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jmbm`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmbm`.`alumno` (
  `idalumno` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `tipodocumento` VARCHAR(45) NULL,
  `ndocumento` INT(10) NULL,
  `edad` INT(10) NULL,
  `codigo` INT(10) NULL,
  `direccion` VARCHAR(80) NULL,
  `grupo_idgrupo` INT NOT NULL,
  PRIMARY KEY (`grupo_idgrupo`, `idalumno`),
  CONSTRAINT `fk_alumno_grupo1`
    FOREIGN KEY (`grupo_idgrupo`)
    REFERENCES `jmbm`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jmbm`.`profesor_has_grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmbm`.`profesor_has_grado` (
  `profesor_idprofesor` INT NOT NULL,
  `grado_idgrado` INT NOT NULL,
  PRIMARY KEY (`profesor_idprofesor`, `grado_idgrado`),
  INDEX `fk_profesor_has_grado_grado1_idx` (`grado_idgrado` ASC),
  INDEX `fk_profesor_has_grado_profesor_idx` (`profesor_idprofesor` ASC),
  CONSTRAINT `fk_profesor_has_grado_profesor`
    FOREIGN KEY (`profesor_idprofesor`)
    REFERENCES `jmbm`.`profesor` (`idprofesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesor_has_grado_grado1`
    FOREIGN KEY (`grado_idgrado`)
    REFERENCES `jmbm`.`grado` (`idgrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
